### ISSUE TITLE
Text Editing window

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#15]
Currently in text editing mode a new simplified pure text window opens with no formatting.
It would be much better if we could edit the card in the same window where the user could see how the card text is going to look like immediately.

**Comment by AbduazizKayumov** [comment]
I think it is easier to edit text in a separate window. Just image having a keyboard (that takes almost half of the screen) and editing text on flashcards: you could not see exactly how the card text is going to look like -> you still need to hide the keyboard.

**Comment by greyboxgt** [comment]
Unless you have a scrolling, but it is probably too complicated.

**Comment by AbduazizKayumov** [comment]
Unfortunately, the current set editor does not allow us to have this feature. Let's say user wants to type a very long text: 20 lines -> I am sure, it would be weird to have "scrolling" text on a flashcard and when you hide the keyboard, the flashcard text needs to scroll back to the first line. 
The separate text editor window was asked and still being asked in the previous version:
https://play.google.com/store/apps/details?id=com.piapps.flashcard
The prev. version had kindda "in-place" editing.
So I switched to have a separate editing window because of 2 reasons:
- "In-place" editing was bad experience according to the  prev. app.
- Separate editing window will allow me to add new features: formatting text (bold, italic ..), text font type and everything you could play with text.
